git-poach: Make sure we are in correct directory

diff --git a/git-poach b/git-poach
--- a/git-poach
+++ b/git-poach
@@ -1,16 +1,28 @@
 #!/bin/bash
 
-SRC_FILE=$1
-DEST_DIR=$2
+SOURCE=$1
+SRC_DIRNAME=$(dirname $SOURCE)
+SRC_FILE=$(basename $SOURCE)
+
+ck_dir () {
+    if [[ -d $1 ]]
+    then
+        cd $1
+        /bin/pwd
+    else
+        echo "ERROR: '$1' not a directory"
+        exit 1
+    fi
+}
+
+SRC_DIR=$(ck_dir $SRC_DIRNAME)
+DEST_DIR=$(ck_dir "$2")
 
 if [[ -z "$DEST_DIR" ]]
 then
     echo "Usage: $0 SOURCE_FILE DESTINATION_DIRECTORY"
     exit 1
 fi
-
-SRC_DIR=$(dirname $SRC_FILE)
-SRC_BASE=$(basename $SRC_FILE)
 
 if [[ -d $DEST_DIR/.git/rebase-apply ]]
 then
